[workspace]
resolver = "2"
members = ["crates/cffdrs-core", "crates/cffdrs-py"]

[workspace.package]
edition = "2021"
license = "MIT"
rust-version = "1.78"
repository = "https://github.com/gagreene/cffdrs"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "warn"
missing_debug_implementations = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
