"""FBP regression gate for the cffbps refactor.

Three layers of protection:

1. ``test_scalar_matches_published_wotton2009`` — a *physical* sanity check that the
   current model reproduces the authoritative Wotton (2009) published values (loose
   tolerance; guards against gross scientific breakage).
2. ``test_scalar_snapshot`` — exact-equality lock of all 54 outputs for the 20 scalar
   test cases against the committed golden. This is the primary anti-drift gate.
3. ``test_array_snapshot`` — same exact-equality lock for the array/masked-array code
   path, driven from the input rasters.

Goldens are regenerated by ``tools/gen_fbp_goldens.py`` from known-good code. Per §0
flag 1, they were rebuilt fresh (the previously committed rasters were stale).
"""
from __future__ import annotations

import json
import os
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import _wotton_helpers as wh  # noqa: E402

from cffdrs.cffbps import FBP  # noqa: E402

# ── Published Wotton (2009) reference (authoritative external oracle) ──────────
# Column indices in Reference_Results.xlsx for the "Wotton 2009" source of each metric.
_WOTTON_COLS = {"fire_type": 15, "hros": 18, "hfi": 21, "cfb": 24, "wsv": 27, "raz": 30}
_FIRE_TYPE_LETTER = {1: "S", 2: "I", 3: "C"}


def _load_scalar_golden() -> dict:
    with open(wh.SCALAR_GOLDEN) as fh:
        return json.load(fh)


def _load_array_golden() -> dict:
    with open(wh.ARRAY_GOLDEN) as fh:
        return json.load(fh)


@pytest.fixture(scope="module")
def scalar_golden() -> dict:
    return _load_scalar_golden()


@pytest.fixture(scope="module")
def array_golden() -> dict:
    return _load_array_golden()


# ── Layer 1: physical validation against published Wotton (2009) values ───────
def _angular_diff(a: float, b: float) -> float:
    """Smallest absolute difference between two azimuths in degrees (0 == 360)."""
    d = abs(a - b) % 360.0
    return min(d, 360.0 - d)


def test_scalar_matches_published_wotton2009():
    """Current outputs must track the published Wotton (2009) values.

    Tolerances are loose on purpose: cross-implementation rounding differs. This
    catches gross regressions, not the sub-percent drift covered by the snapshot.

    ``raz`` is compared as a circular azimuth (0 == 360). One case is exempt for raz:
    id 17 has no wind AND no slope, so the spread azimuth is mathematically undefined
    (code yields 360, published 180 — a documented degenerate case). Magnitudes near
    zero use an absolute tolerance rather than relative.
    """
    pd = pytest.importorskip("pandas")
    ref = pd.read_excel(
        os.path.join(wh.DATA_DIR, "Reference_Results.xlsx"),
        sheet_name="Results", header=None,
    ).iloc[2:22].reset_index(drop=True)

    df = wh.load_input_frame()
    out_req = ["fire_type", "hros", "hfi", "cfb", "wsv", "raz"]
    raz_exempt = {17}  # no wind + no slope -> undefined azimuth

    for i, (_, row) in enumerate(df.iterrows()):
        cid = int(row["id"])
        fbp = FBP()
        fbp.initialize(**wh.row_to_kwargs(row, out_req))
        got = dict(zip(out_req, (wh.scalarize(v) for v in fbp.runFBP())))

        # Fire type: exact category match (numeric -> S/I/C letter).
        assert _FIRE_TYPE_LETTER.get(got["fire_type"]) == str(ref.iloc[i, _WOTTON_COLS["fire_type"]]), \
            f"case {cid}: fire_type {got['fire_type']} != {ref.iloc[i, _WOTTON_COLS['fire_type']]}"

        for metric in ("hros", "hfi", "cfb", "wsv", "raz"):
            published = float(ref.iloc[i, _WOTTON_COLS[metric]])
            current = got[metric]
            assert current is not None, f"case {cid}: {metric} is None"

            if metric == "raz":
                if cid in raz_exempt:
                    continue
                diff = _angular_diff(current, published)
                assert diff < 1.0, f"case {cid} raz: {diff:.3f}deg apart (got {current}, pub {published})"
            elif abs(published) < 0.1:
                assert abs(current - published) < 0.1, f"case {cid} {metric}: {current} vs ~{published}"
            else:
                rel = abs(current - published) / abs(published)
                assert rel < 0.02, f"case {cid} {metric}: rel err {rel:.3%} (got {current}, pub {published})"


# ── Layer 2: exact-equality snapshot lock, scalar path ────────────────────────
def test_scalar_snapshot(scalar_golden):
    """Every scalar output for all 20 cases must exactly match the golden."""
    outputs = scalar_golden["outputs"]
    df = wh.load_input_frame()
    by_id = {int(r["id"]): r for _, r in df.iterrows()}

    mismatches = []
    for case in scalar_golden["cases"]:
        row = by_id[case["id"]]
        fbp = FBP()
        fbp.initialize(**wh.row_to_kwargs(row, outputs))
        got = dict(zip(outputs, (wh.scalarize(v) for v in fbp.runFBP())))
        for name in outputs:
            if got[name] != case["outputs"][name]:
                mismatches.append(
                    f"  id {case['id']} [{case['fuel_type_code']}] {name}: "
                    f"got {got[name]!r} != golden {case['outputs'][name]!r}"
                )
    assert not mismatches, "scalar snapshot drift:\n" + "\n".join(mismatches)


# ── Layer 3: exact-equality snapshot lock, array/masked-array path ────────────
def test_array_snapshot(array_golden):
    """Every array output must exactly match the golden (masked-array code path)."""
    pytest.importorskip("rasterio")
    outputs = array_golden["outputs"]
    fbp = FBP()
    fbp.initialize(out_request=outputs, **wh.load_raster_inputs())
    result = dict(zip(outputs, (wh.arrayize(v) for v in fbp.runFBP())))

    mismatches = []
    for name in outputs:
        if result[name] != array_golden["arrays"][name]:
            mismatches.append(f"  {name}:\n    got    {result[name]}\n    golden {array_golden['arrays'][name]}")
    assert not mismatches, "array snapshot drift:\n" + "\n".join(mismatches)
